using System;
using System.Collections.Generic;
using System.Text;

namespace HypervisorSharp.Mac
{
    public enum HvReg
    {
        RIP,
        RFLAGS,
        RAX,
        RCX,
        RDX,
        RBX,
        RSI,
        RDI,
        RSP,
        RBP,
        R8,
        R9,
        R10,
        R11,
        R12,
        R13,
        R14,
        R15,
        CS,
        SS,
        DS,
        ES,
        FS,
        GS,
        IDT_BASE,
        IDT_LIMIT,
        GDT_BASE,
        GDT_LIMIT,
        LDTR,
        LDT_BASE,
        LDT_LIMIT,
        LDT_AR,
        TR,
        TSS_BASE,
        TSS_LIMIT,
        TSS_AR,
        CR0,
        CR1,
        CR2,
        CR3,
        CR4,
        DR0,
        DR1,
        DR2,
        DR3,
        DR4,
        DR5,
        DR6,
        DR7,
        TPR,
        XCR0
    }
}
